### PR TITLE
issue-1123: fix encoded url

### LINKED ISSUE #1123: [Regional contacts] UI issues
Reported by @MeghnaTewari in #1055

1. There is inconsistency in the arrow icons after Contact your local Sales Team CTA, for some regions it shows and for some it doesn't. Check my screenshot for Albania
image

2. Inconsistency in external icons as well
image
 visible for some countries, example- US
image

3. Please fix the URL for this page
https://www.moleculardevices.com/contact-search?country=United%20States&product_family=

should be

https://live-md30.pantheonsite.io/contact-search?data=submit

### PR DESCRIPTION
**Pull request by alinarublea**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #1123 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/contact?region=americas
- After: https://issue-1123-url--moleculardevices--hlxsites.hlx.page/contact?region=americas

### CODE REVIEW

File: blocks/local-distributor/local-distributor.js [hunk 1]
```diff
@@ -84,45 +84,54 @@ function hideResult() {
...
+  window.open(`/contact-search?country=${distributorsMap[countryName]}&product_family=${primeProduct ? productFamilyMap[primeProduct] : ''}`, '_blank');
   Event.preventDefault();
 }
 
 export default async function decorate(block) {
   const params = queryString();
 
-  const distributors = await ffetch('/contact/local-distibutors.json').withFetch(fetch).all();
-  const productFamilyList = await ffetch('/contact/local-distibutors.json')
+  const distributors = await ffetch('/drafts/mhaack/local-distibutors.json').withFetch(fetch).all();
```
Comment (alinarublea) [inline blocks/local-distributor/local-distributor.js:97]: TODO change updated just for testing purposes
