### PR TITLE
169 breadcrumb exceptions

### LINKED ISSUE #169: Breadcrumb implement exceptions
Kapil Dhiman
  [5 hours ago](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1680695540120849)
Hi 
[@Paolo Mottadelli](https://adobe-dx-support.slack.com/team/U041RT3N6T0)
 this is regarding breadcrumbs
We had a discussion on breadcrumbs and here is the feedback.
Breadcrumb will follow the URL structure but the last slash in pathname will be replaced with the h1 of the page.
 Need to exclude some path from breadcrumb e.g ['en', 'assets', 'br', 'img'], etc. We'll provide the final array that should be excluded
 Some paths in Breadcrumb don't have URLs so they will have a custom URL e.g.
	[
	'app-note' => 'https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BApplication%20Note%5D[',](https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BApplication%20Note%5D',)
	'ebook' => 'https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BeBook%5D['](https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BeBook%5D')
	]
	we'll provide the final list.
Please let me know if you've any concerns.

Kapil Dhiman
  [1 hour ago](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1680707357854439?thread_ts=1680695540.120849&cid=C04QNDDUADT)
to exclude the path I am taking an e.g. of this url
https://www.moleculardevices.com/en/assets/customer-breakthrough/br/university-of-california-davis
en, assets & br wont be part of the breadcrumb
Molecular DevicesMolecular Devices
[University of California, Davis uses the MultiWash washer to engineer replacement and temporal bridge tissue](https://www.moleculardevices.com/en/assets/customer-breakthrough/br/university-of-california-davis)
Leach Laboratory at UC Davis focuses on cellular and tissue engineering. Kaitlin Murphy helps engineer functional replacement and temporary bridge tissues.

Kapil Dhiman
  [1 hour ago](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1680707757976979?thread_ts=1680695540.120849&cid=C04QNDDUADT)
in the same way, there will be another path to exclude

Kapil Dhiman
  [1 hour ago](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1680708093822509?thread_ts=1680695540.120849&cid=C04QNDDUADT)
For above url breadcrumb should be
Home -> Customer Breakthrough -> University of California, Davis uses the MultiWash washer to engineer replacement and temporal bridge tissue

Kapil Dhiman
  [1 hour ago](https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1680708256032039?thread_ts=1680695540.120849&cid=C04QNDDUADT)
In 2nd case e.g.
https://www.moleculardevices.com/en/assets/app-note/bpd/easy-picking-with-qpix-400
In this url need to exclude 'en', 'assets', 'abd' and need to add custom  link for app-note
so breadcrub should be
Home -> App Note -> Easy picking with the QPix 400: multiple selection modalities, wide range of microorganisms
and App Note should point to https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=[Application%20Note]
Molecular DevicesMolecular Devices
[Easy picking with the QPix 400: multiple selection modalities, wide range of microorganisms](https://www.moleculardevices.com/en/assets/app-note/bpd/easy-picking-with-qpix-400)
Explore QPix colony pickers that support a wide variety of microorganisms & multiple selection modalities, including fluorescence intensity, blue/white selection, size & proximity.

### PR DESCRIPTION
**Pull request by paolomoz**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #169

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer
- After: https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.live/products/axon-patch-clamp-system/digitizers/axon-digidata-1550b-plus-humsilencer

### CODE REVIEW

File: blocks/breadcrumbs/breadcrumbs-create.js [hunk 1]
```diff
@@ -17,21 +17,38 @@ function createBreadcrumbListItem(crumb) {
   return li;
 }
 
+function skipParts(pathSplit) {
+  const partsToSkip = ['en', 'assets', 'br', 'img'];
+  return pathSplit.filter((item) => !partsToSkip.includes(item));
+}
+
+function getCustomUrl(part) {
```
Comment (duynguyen) [inline blocks/breadcrumbs/breadcrumbs-create.js:25]: wondering if `customUrls` can be an object instead of a nested array? code would be simpler and better performance:
```
function getCustomUrl(part) {
  const customUrls = {
    'app-note': 'https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BApplication%20Note%5D',
    'ebook': 'https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=%5BeBook%5D',
  };
  return customUrls[part] || null;
}
```

File: blocks/breadcrumbs/breadcrumbs-create.js [hunk 2]
```diff
@@ -17,21 +17,38 @@ function createBreadcrumbListItem(crumb) {
...
     {
       name: 'Home',
       url_path: '/',
     },
-    ...currentPath.split('/').slice(1, -1).map((part, index) => ({
-      name: pageIndex.find((page) => page.path === urlForIndex(index))?.title ?? part,
-      url_path: urlForIndex(index),
+    ...pathSplit.slice(1, -1).map((part, index) => ({
+      name: pageIndex.find((page) => page.path === urlForIndex(index))?.h1 ?? part,
+      url_path: getCustomUrl(part) ? getCustomUrl(part) : urlForIndex(index),
```
Comment (duynguyen) [inline blocks/breadcrumbs/breadcrumbs-create.js:49]: simplified version: `url_path: getCustomUrl(part) || urlForIndex(index),` (which might give better performance as `getCustomUrl` is always called once only.

**Review by andreituicu — COMMENTED** [review]
I tested with: https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.live/en/assets/customer-breakthrough/br/etap-lab

and it looks like the breadcrumb is broken in this case.

Screenshot 2023-04-14 at 19 11 07

The parts to be skipped were indeed missing, but the `0` in the end looks like a bug. The result from the index will be `"0"` for empty values, not `undefined` or `null`, so I think there may be a problem with that condition.

In https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/measure-intrinsic-tryptophan-fluorescence-on-spectramax-id3-microplate-reader

File: blocks/breadcrumbs/breadcrumbs-create.js (hunk 1 above)
Comment (paolomoz) [reply blocks/breadcrumbs/breadcrumbs-create.js:25]: thank you @duynguyen I agree it would be simpler to read. Why are you suggesting that it would also be good for performance? I am reading the opposite somewhere https://stackoverflow.com/questions/32520755/performance-between-multidimensional-array-or-arrays-of-objects-in-javascript, https://stackoverflow.com/questions/17295056/array-vs-object-efficiency-in-javascript, https://medium.com/@mahesh_joshi/javascript-performance-array-vs-object-794f1e30e920
And we are foreseeing just a handful of entries here.
All in all I would defer this improvement and move ahead with this PR

Comment (duynguyen) [reply blocks/breadcrumbs/breadcrumbs-create.js:25]: I also stumbled upon [your second reference](https://stackoverflow.com/questions/17295056/array-vs-object-efficiency-in-javascript), which suggests that retrieving value by looping through an array is way slower than getting value by key in an object (51ms vs. 1049ms for a set of 2000 values). However there's almost no diff if the set contains only a few items.
Therefore, as long as this set does not grow to 100 or so, I agree with you we could keep it as is.

FWIW, not directly to this PR but to the other references: they compare looping through the whole set in both cases (array and object). Then it's definitely faster with array, because for object you have to run the loop anyway plus getting the value by key.

**Review by duynguyen — APPROVED** [review]

**Review by andreituicu — APPROVED** [review]
Approving as I'd like to have the code in while optimising the LCP. I saw that the breadcrumb was contributing to that.

One thing is not 100% clear to me, for: https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/measure-intrinsic-tryptophan-fluorescence-on-spectramax-id3-microplate-reader

It is 
-> ❓  `measure-intrinsic-tryptophan-fluorescence-on-spectramax-id3-microplate-reader`
instead of 
-> ✅  `Measure intrinsic tryptophan fluorescence on the SpectraMax iD3 microplate reader`. 

Got a comment about that here: https://github.com/hlxsites/moleculardevices/pull/201#issuecomment-1510926986 .

**Comment by andreituicu** [comment]
> for: https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/measure-intrinsic-tryptophan-fluorescence-on-spectramax-id3-microplate-reader

answered my own question 🙂 that page was only previewed and not published, so it is not indexed.

**Comment by paolomoz** [comment]
> > for: https://169-breadcrumb-exceptions--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/measure-intrinsic-tryptophan-fluorescence-on-spectramax-id3-microplate-reader
> 
> answered my own question 🙂 that page was only previewed and not published, so it is not indexed.

@andreituicu in any case I added an additional fallback before using the path: if it is current page get document.title
https://github.com/hlxsites/moleculardevices/pull/189/commits/3181801526ae64a865a16f94a6f8119887fc6c6e
