### PR TITLE
[Issue 530] Fix filter behaviour to work with multiregion and multitype events

### LINKED ISSUE #530: [Events] Overview page region filter should not combine regions
Where: https://main--moleculardevices--hlxsites.hlx.page/events

What: Region filter currently only shows the regions from the existing events. If an event is both in NA and Europe, it should display in both filtered results of NA and Europe. There should not be a filter called "NA, Europe".

### PR DESCRIPTION
**Pull request by alexcarol**
Fix #530 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/archived-events
- After: https://issue-530--moleculardevices--hlxsites.hlx.page/archived-events

### CODE REVIEW

File: blocks/events/events.js [hunk 1]
```diff
@@ -8,8 +8,10 @@ import {
 } from '../../scripts/dom-helpers.js';
 
 function prepareEntry(entry, showDescription, viewMoreText) {
-  entry.filterEventType = toClassName(entry.eventType);
-  entry.filterEventRegion = toClassName(entry.eventRegion);
+  entry.filterEventType = entry.eventType.split(', ')
```
Comment (duynguyen) [inline blocks/events/events.js:11]: safer to split by ',' (no space) and trim the string, because sometimes space might be missed.

Comment (alexcarol) [reply blocks/events/events.js:11]: good idea, will do

**Review by lydiapuric — APPROVED** [review]
+1
