### PR TITLE
1078 - [High priority] cmp cookie not working on landing pages

### LINKED ISSUE #1078: [High priority] cmp cookie not working on landing pages
Hi Team,

Leads not routing to SFDC campaign added onto the end of URL with ?cmp=

### PR DESCRIPTION
**Pull request by andreituicu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #1078

Test URLs:
Without a custom campaign ID:
- Before: https://main--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis
- After: https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis

With a custom campaign ID:
- Before: https://main--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis?cmp=xyz
- After: https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis?cmp=xyz

### CODE REVIEW

File: templates/landing-page/landing-page.js [hunk 1]
```diff
@@ -13,6 +13,23 @@ async function iframeResizeHandler() {
...
+        const url = new URL(href);
+        if (url.searchParams.get('cmp')) {
+          url.searchParams.set('cmp', cmpCookieValue);
+          link.setAttribute('href', url.toString());
+        }
+      });
+    }
+  } catch (err) {
+    // eslint-disable-next-line no-console
+    console.log(`Failed to change the campaing ID: ${err.message}`);
```
Comment (duynguyen) [inline templates/landing-page/landing-page.js:30]: could use console.error

**Review by duynguyen — APPROVED** [review]
LGTM. just a minor comment

**Review by lydiapuric — APPROVED** [review]
LGTM +1
