### PR TITLE
issue-873 - [Products] Broken product comparison table and UI issues

### LINKED ISSUE #873: [Products] Broken product comparison table and UI issues
https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers
https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

Fix the specifications table on both the pages.

image

Also,
1. Fix the large h2 titles 
2. Under "applications and assays" fix bullets alignment, add arrow icon and fix spacing between the TOC bullets
3. Centre align the titles
4. Add anchor link on view products CTA in the banner

https://franklin.moleculardevices.com/products/microplate-readers/multi-mode-readers

image
image
image

https://franklin.moleculardevices.com/products/microplate-readers/absorbance-readers

image
image
Reduce img size 
image

https://franklin.moleculardevices.com/products/microplate-readers/fluorescence-readers
https://franklin.moleculardevices.com/products/microplate-readers/luminescence-readers

Reduce font size and make it blue 

image
image

### PR DESCRIPTION
**Pull request by alinarublea**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #873 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers
- After: https://issue-873--moleculardevices--hlxsites.hlx.page/products/microplate-readers/absorbance-readers

### CODE REVIEW

**Comment by alinarublea** [comment]
TODO:
1.Dynamic and correct resizing of the table
2. Scroll functionality in the scroll bar not only with the - and +
3. Check why I get an extra column in the data

**Comment by mhaack** [comment]
We agreed earlier we will only have one common style for the comparison tables.

**Comment by duynguyen** [comment]
ok I got the unified table style which also makes sense to me.
The problem is with this new style, some products don't have the required data e.g. `description`.
@alinarublea could you double check the missing data in other tables and add add those content if available or at least a null check?

**Comment by alinarublea** [comment]
Yes, I will add the missing data for all of them, I also need to add the thumbnails

File: blocks/product-comparison/product-comparison.js [hunk 1]
```diff
@@ -36,12 +36,12 @@ export default async function decorate(block) {
...
-        a({ href: productSpec.path },
-          createOptimizedPicture(productSpec.thumbnail),
-          p(productSpec.title),
-        ),
-      ),
-    ));
+        div({ class: 'product-heading-title darkgrey' }, productSpec.title),
+        createOptimizedPicture(productSpec.thumbnail),
+        p(productSpec.description),
+        a({ href: productSpec.path, class: 'product-info-btn' }, 'PRODUCT INFO'),
```
Comment (duynguyen) [inline blocks/product-comparison/product-comparison.js:42]: let's add a placeholder for `PRODUCT INFO` to have it translated.

File: blocks/product-comparison/product-comparison.css [hunk 2]
```diff
@@ -80,6 +100,55 @@
...
+  align-items: center;
+  justify-content: center;
+}
+
+.product-comparison .responsive-table .product-info-btn  {
+  color: var(--button-bg-color);
+  border: 2px solid var(--button-bg-color);
+}
+
+.product-comparison .responsive-table a {
```
Comment (duynguyen) [inline blocks/product-comparison/product-comparison.css:116]: is this for `product-info-btn` specifically instead of generic link?

File: blocks/product-comparison/product-comparison.css [hunk 3]
```diff
@@ -80,6 +100,55 @@
...
+  font-size: 13px;
+  display: inline-block;
+  text-decoration: none;
+  text-transform: uppercase;
+  margin: 5px 0 10px;
+  font-family: var(--ff-proxima-regular);
+  transition: all .3s;
+}
+
+.product-comparison .responsive-table a:hover {
```
Comment (duynguyen) [inline blocks/product-comparison/product-comparison.css:127]: is this for `product-info-btn` specifically instead of generic link?

Comment (alinarublea) [reply blocks/product-comparison/product-comparison.css:127]: Yes, I will use product-info-btn instead

**Comment by alinarublea** [comment]
> ok I got the unified table style which also makes sense to me. The problem is with this new style, some products don't have the required data e.g. `description`. @alinarublea could you double check the missing data in other tables and add add those content if available or at least a null check?

@duynguyen I added the null check, because there was no description in the original site

File: k8s-kubeconfig
Comment (mhaack) [inline k8s-kubeconfig:1]: Remove this, should not be in git
