### PR TITLE
861 - Product Comparison functionality is not working

### LINKED ISSUE #861: Product Comparison functionality is not working
https://franklin.moleculardevices.com/products/microplate-readers
https://franklin.moleculardevices.com/products/additional-products

Product comparison functionality is not working on some pages. After selecting products and clicking on the compare button, nothing happens.

### PR DESCRIPTION
**Pull request by andreituicu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #861

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/products/microplate-readers
- After: https://fix-compare--moleculardevices--hlxsites.hlx.live/products/microplate-readers

- Before: https://main--moleculardevices--hlxsites.hlx.live/products/additional-products
- After: https://fix-compare--moleculardevices--hlxsites.hlx.live/products/additional-products

### CODE REVIEW

File: templates/compare-items/compare-modal.js [hunk 1]
```diff
@@ -77,10 +85,11 @@ class CompareModal {
     return json;
   }
 
-  parseSpecificationsSheet(path, json) {
+  parseSpecificationsSheet(info, json) {
+    console.log(info);
```
Comment (mhaack) [inline templates/compare-items/compare-modal.js:89]: Please remove

**Review by mhaack — APPROVED** [review]
